### Problem 17 ###
If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?

NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.

### ideas
first of all we dont need to know the letters, just the number of them

In [1]:
import numpy as np

In [2]:
xs = np.arange(1,10)

In [3]:
xs

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
'from 1 to 5 we have 19 letters'
six = 3
seven = 5
eight = 5
nine = 4

from 1 to 100 we have (one to ten)
eleven to nineteen

10*twenty something
10*thirty something
10*fourty something
10*...
10*ninety something


In [5]:
twenty = 6
thirty = 6
forty = 5
fifty = 5
sixty = 5
seventy = 7
eigthy = 6
ninety = 6

In [6]:
one = 3
two = 3
three = 5
four = 4
five = 4
six = 3 
seven = 5
eight = 5
nine = 4

In [7]:
numbers = np.array([one,two,three,four,five,six,seven,eight,nine])
numbers

array([3, 3, 5, 4, 4, 3, 5, 5, 4])

In [8]:
ttnin = np.array([twenty,thirty,forty,fifty,sixty,seventy,eigthy,ninety])
ttnin

array([6, 6, 5, 5, 5, 7, 6, 6])

In [9]:
ten,eleven,twelve,thirteen,fourteen,fifteen,sixteen,seventeen,eighteen,nineteen = 3,6,6,8,8,7,7,9,8,8

In [10]:
broken = np.array([ten,eleven,twelve,thirteen,fourteen,fifteen,sixteen,seventeen,eighteen,nineteen])

In [11]:
broken

array([3, 6, 6, 8, 8, 7, 7, 9, 8, 8])

In [12]:
hundredand = 10

In [13]:
# sum from one to ninety nine = 
otnn = sum(numbers*9) + sum(broken) + sum(ttnin*10) 

In [14]:
otnn

854

In [15]:
numbersh = numbers + 7 # hundreds

In [16]:
numbersh

array([10, 10, 12, 11, 11, 10, 12, 12, 11])

In [17]:
numbersha = numbersh + 3

In [18]:
 hundredd = numbersha * 99 + numbersh

In [19]:
hundredd

array([1297, 1297, 1497, 1397, 1397, 1297, 1497, 1497, 1397])

In [20]:
onethousand = 3 + 8

In [21]:
10*otnn+ onethousand + sum(hundredd)

21124